version: "2.4"

services:
  coaliter:
    env_file: ./.env
    build:
      context: .
    image: ketchup.pizza/coaliter:${COALITER_VER}
    environment:
      State__ConnectionString: "Data Source=/app/state/state.db"
    volumes:
      - ./state:/app/state
    ports:
      - "5000:80"